FROM __BASEIMAGE_ARCH__/node:slim
__CROSS_COPY qemu-__QEMU_ARCH__-static /usr/bin/
COPY package*.json /usr/src/
COPY . /usr/src/
WORKDIR /usr/src/
RUN npm install
EXPOSE 8080
CMD ["node","index.js"]